keys:
  - &master  age1g24xxtf3hxldudfedy74gtzg25ygrzjzd5zr9g0m3pw8vegxydeqvs5xxm
  - &desktop age1tfz3wsnre7yn6k43gsasx6tw2rf7h27gda7rdvu9l3wqxr4hca6qpy2j4v
  - &laptop  age1evl3qa9amaznmv37a85kjha9jxgd6kn2j5jkqj0nvvc6ggfgxd4qhvflnw
  - &wsl     age1z0zu80qx8xrgkjm4hmwevmz8acmye3wstef5mx9lsfd3xsz09a8szkxjg7

creation_rules:
  - path_regex: secrets.yaml$
    key_groups:
      - age: [ *master, *desktop, *laptop, *wsl ]
