{
  mkEnableOption,
  mkOption,
  types,
}:
let
  mkStrOption =
    description:
    mkOption {
      inherit description;
      type = types.str;
    };
in
{
  enable = mkEnableOption ''
    Turn on the mailserver module and provision Postfix/Dovecot.
    Enable only when the host should accept and deliver email locally.
  '';

  enableIpV6 = mkEnableOption ''
    Configure IPv6 addresses and firewall rules for the mail stack.
    Enable when the host has routed IPv6 connectivity for mail services.
  '';

  ipV6Address = mkStrOption ''
    IPv6 address assigned to the network interface hosting mail services.
    Used to configure static bindings and advertised endpoints.
  '';

  ipV6Interface = mkStrOption ''
    Network interface name that carries the IPv6 address for mail.
    Referenced when configuring interface-specific IPv6 settings.
  '';

  domain = mkStrOption ''
    Fully-qualified domain name that users connect to for mail.
    Typically points at the host's MX and service records.
  '';

  baseDomain = mkStrOption ''
    Base zone you control for publishing MX and SRV records.
    Used for autogenerated aliases and ACME certificate requests.
  '';

  providerName = mkStrOption ''
    Human-readable provider name advertised via AutoMX.
    Appears in client autoconfiguration dialogs.
  '';

  smtpPort = mkOption {
    type = types.port;
    default = 587;
    description = ''
      TCP port used by the SMTP service (submission).
      Common values: 587 (submission, STARTTLS) or 465 (smtps, implicit TLS).
    '';
  };

  imapPort = mkOption {
    type = types.port;
    default = 993;
    description = ''
      TCP port used by the IMAP service (message retrieval).
      Common values: 993 (imaps, implicit TLS) or 143 (imap, STARTTLS).
    '';
  };

}
