{ lib, ... }:
let
  mkStrOption =
    description:
    lib.mkOption {
      inherit description;
      type = lib.types.nullOr lib.types.str;
    };
in
{
  options.hostPrefs.mailserver = {

    enable = lib.mkEnableOption "Enable mailserver, Postfix, and Dovecot for local email acceptance and delivery.";
    domain = mkStrOption "Primary zone for MX/SRV records, autogenerated aliases, and ACME certificate requests.";
    providerName = mkStrOption "Human-readable name displayed in client autoconfiguration dialogs via AutoMX.";

    extraDomains = lib.mkOption {
      type = lib.types.listOf lib.types.str;
      default = [ ];
      description = "List of additional subdomains of the specified domain authorized for email delivery.";
    };

    smtpPort = lib.mkOption {
      type = lib.types.port;
      default = 587;
      description = ''
        TCP port used by the SMTP service (submission).
        Common values: 587 (submission, STARTTLS) or 465 (smtps, implicit TLS).
      '';
    };

    imapPort = lib.mkOption {
      type = lib.types.port;
      default = 993;
      description = ''
        TCP port used by the IMAP service (message retrieval).
        Common values: 993 (imaps, implicit TLS) or 143 (imap, STARTTLS).
      '';
    };
  };
}
