host_keys:
  - &desktop  age176puuxxhdn3r23z4885q9eu62xv0rjhyyfrkrnwtdyflfgn7py8s0rxeay
  - &lab      age1jnxe06pen0p6t3776lrxyzhwft85mhxq834cjak5ujvnfuta5sls0gahhj
  - &laptop   age1u3gzkpuv4ejs0ncwwk0l07adpz0r8nfyje8nmwpsxlqsssthhpmqcuyfqm
  - &server   age1tk5c54e5ys9hstm5qcjprul0qedh78wvzvpc9zvdp9jgnvz5xs7ql425tv

trivaris_keys:
  - &trivaris_desktop age1egv6ruakcsfn4g3eqth6ues3m275c95s459vakcmxcwv080gayyqejf2wr
  - &trivaris_lab     age1l7732fcmkwkjrn8ewvuz0tr6474raypnzfc6tj6wst9lty9ljqeqvz380t
  - &trivaris_laptop  age1365s7nzs6rdfwhf0gham478z3sx0jdc9wkhg5qm6wjnc9pwhf9gsr8vn6r
  - &trivaris_server  age1hjv38pcnfv99xdtmgx3ull3m9c0467rad7er4sjrtfzwpp7a65usy3cr29

creation_rules:
  # Shared host secrets (all hosts)
  - path_regex: host/common.yaml$
    key_groups:
      - age: [ *server, *lab, *laptop, *desktop ]

  # Host-specific secrets
  - path_regex: host/desktop.yaml$
    key_groups:
      - age: [ *desktop ]

  - path_regex: host/lab.yaml$
    key_groups:
      - age: [ *lab ]

  - path_regex: host/laptop.yaml$
    key_groups:
      - age: [ *laptop ]

  - path_regex: host/server.yaml$
    key_groups:
      - age: [ *server ]

  # User-specific secrets
  - path_regex: home/trivaris/common.yaml$
    key_groups:
      - age: [ *trivaris_desktop, *trivaris_lab, *trivaris_laptop, *trivaris_server ] 

  - path_regex: home/trivaris/desktop.yaml$
    key_groups:
      - age: [ *trivaris_desktop ]

  - path_regex: home/trivaris/lab.yaml$
    key_groups:
      - age: [ *trivaris_lab ]

  - path_regex: home/trivaris/laptop.yaml$
    key_groups:
      - age: [ *trivaris_laptop]
  
  - path_regex: home/trivaris/server.yaml$
    key_groups:
      - age: [ *trivaris_server ]
