host_keys:
  - &desktop  age176puuxxhdn3r23z4885q9eu62xv0rjhyyfrkrnwtdyflfgn7py8s0rxeay
  - &laptop   age1u3gzkpuv4ejs0ncwwk0l07adpz0r8nfyje8nmwpsxlqsssthhpmqcuyfqm
  - &wsl      age17x0pgadrcvgana6vun9jjvvf3a8c8xlqgpg5uhlq2dl6nr50ms4qy7nj3y

trivaris_keys:
  - &trivaris_desktop age1hvtndjpj2anaxvpear4rg50kl3qngtwghqh3dmxhdpwz02q9kgfqx5j3rt
  - &trivaris_laptop  age1365s7nzs6rdfwhf0gham478z3sx0jdc9wkhg5qm6wjnc9pwhf9gsr8vn6r
  - &trivaris_wsl     age1g6hfk3djtmn8lc8qgc7hhyks62skza8y2hcc6h2a32ru5x0faf9svhrt40

creation_rules:
  # Shared host secrets (all hosts)
  - path_regex: hosts/common.yaml$
    key_groups:
      - age: [ *desktop, *laptop, *wsl ]

  # Host-specific secrets
  - path_regex: hosts/desktop.yaml$
    key_groups:
      - age: [ *desktop ]

  - path_regex: hosts/laptop.yaml$
    key_groups:
      - age: [ *laptop ]

  - path_regex: hosts/wsl.yaml$
    key_groups:
      - age: [ *wsl ]

  # User-specific secrets
  - path_regex: home/trivaris/common.yaml$
    key_groups:
      - age: [ *trivaris_desktop, *trivaris_laptop, *trivaris_wsl] 

  - path_regex: home/trivaris/desktop.yaml$
    key_groups:
      - age: [ *trivaris_desktop ]
  
  - path_regex: home/trivaris/laptop.yaml$
    key_groups:
      - age: [ *trivaris_laptop]
  
  - path_regex: home/trivaris/wsl.yaml$
    key_groups:
      - age: [ *trivaris_wsl ]
